export const STORIES_GET_ALL = 'STORIES_GET_ALL';
export const STORIES_GET_ALL_SUCCESS = 'STORIES_GET_ALL_SUCCESS';
export const STORIES_ATTACH_ALL_SUCCESS = 'STORIES_ATTACH_ALL_SUCCESS';
export const STORIES_GET_ALL_ERROR = 'STORIES_GET_ALL_ERROR';
